name: Mirroring

on: [push, delete]

jobs:
  CodeCommit:                                        # <-- different jobs are executed in parallel.
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1

    - name: Setup python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run : |
        python -m pip install -U pip
        pip install -r requirements-cdk.txt

    - name: Setup AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id    : ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
        aws-region           : ${{ secrets.AWS_REGION }}

    - name: Install AWS CDK
      uses: actions/setup-node@v2-beta
      with:
        node-version: '12'

    - run : npm install -g aws-cdk
    - run : echo "$(cdk --version)"
    - run : cdk bootstrap
    - run : cdk deploy example-pipeline-pipeline --require-approval=never -c branch=pipeline --progress events

    - uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url:
          ssh://git-codecommit.us-east-1.amazonaws.com/v1/repos/example
        ssh_private_key:
          ${{ secrets.CODECOMMIT_SSH_PRIVATE_KEY }}
        ssh_username   :                                   # <-- (for codecommit) you need to specify ssh-key-id as ssh username.
          ${{ secrets.CODECOMMIT_SSH_PRIVATE_KEY_ID }}